name: CI

on:
  pull_request:
    branches: [ main ]
  schedule:
    # NOTE: UTCなので9時間引く
    # 毎日22時に実行
    - cron: 0 13 * * *
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-20.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.4
          cache: yarn

      - name: Install node packages
        run: yarn install

      - name: Run eslint
        run: yarn lint

      - name: Run test
        run: yarn test
